### ISSUE TITLE
_find_library_header fails on Python 2 if file named with unicode

### ISSUE THREAD

**Issue by ghost** [brianbruggeman/glfw-cffi#2]
Trying to run simple_windows.py example:
```
Traceback (most recent call last):
  File "/home/tiber/bench/glfw-cffi/examples/simple_window.py", line 9, in <module>
    import glfw
  File "/home/tiber/bench/glfw-cffi/glfw/__init__.py", line 42, in <module>
    from .api import *  # noqa
  File "/home/tiber/bench/glfw-cffi/glfw/api.py", line 12, in <module>
    from . import raw
  File "/home/tiber/bench/glfw-cffi/glfw/raw.py", line 522, in <module>
    _ffi, _glfw = _initialize_module(FFI())
  File "/home/tiber/bench/glfw-cffi/glfw/raw.py", line 370, in _initialize_module
    header_path, source = _find_library_header('glfw3', glfw_path, ffi)
  File "/home/tiber/bench/glfw-cffi/glfw/raw.py", line 325, in _find_library_header
    'include' in folder_object)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

```
It's because folder_object is a value from os.listdir(include_path) list, but this code can't handle names of directories like 'Шаблоны' - russian

**Comment by brianbruggeman** [comment]
Sorry for the late reply.  Awesome feedback!  Thanks for this.

I'm completely open to pull requests here, but I'll see what I can do about the unicode issue (this is always tricky with python 2/3 compatibility).
